name: youtube_sentiment
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - streamlit
      - python-dotenv
      - google-api-python-client
      - pandas
      - numpy
      - scikit-learn
      - vaderSentiment
      - textblob
      - plotly
      - matplotlib
      - seaborn
      - wordcloud
      - pytest
